title: Testing Distributed Systems
description: Curated list of resources on testing distributed systems
author: 
  name: Andrey Satarin
  twitter: asatarin
google_analytics: G-6RQFPSJXCJ
show_downloads: false
theme: jekyll-theme-cayman

twitter:
  username: asatarin
  card: summary_large_image

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin

defaults:
  - 
    scope:
      path: ""
    values:
      image: https://asatarin.github.io/assets/thumbnails/default-thumbnail.png

plugins:
  - jekyll-redirect-from

kramdown:
  strict_mode: true
  toc_levels: "1..4"
